name: TWRP Recovery Pie 2026

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Minimal-Manifest Branch'
        required: true
        default: 'twrp-9.0'
        type: choice
        options:
        - twrp-14.1
        - twrp-12.1
        - twrp-11
        - twrp-9.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree' 
        required: true
        default: 'https://github.com/Tec4Sho/device_alps_tb8163p3_bsp.git'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch' 
        required: true
        default: 'android-9.0'
      DEVICE_PATH:
        description: 'DEVICE PATH' 
        required: true
        default: 'device/alps/tb8163p3_bsp'
      DEVICE_NAME:
        description: 'DEVICE NAME' 
        required: true
        default: 'tb8163p3_bsp'
      BUILD_TARGET:
        description: 'BUILD TARGET' 
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      RECOVERY_INSTALLER:
        description: ': RECOVERY INSTALLER'
        type: boolean
        required: false
        default: 'true'
      CLEAN_ENVIRONMENT:
        description: ': CLEAN ENVIRONMENT'
        type: boolean
        required: false
        default: 'true'
      MAXIMIZE_BUILD_SPACE:
        description: ': MAXIMIZE BUILD SPACE'
        type: boolean
        required: false
        default: 'true'
        
jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-22.04-arm
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.TWRP }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Display Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Displaying variables/inputs."
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree: ${{ github.event.inputs.DEVICE_TREE }}"
        echo "Device Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}image"
        echo "Include Recovery Installer: ${{ github.event.inputs.RECOVERY_INSTALLER }}"
        echo "Release recovery.tar For Samsung devices: ${{ github.event.inputs.RECOVERY_TAR }}"
        echo "::endgroup::"
        
    - name: Check disk space
      run: |
        df -h /
        du -sh /* 2>/dev/null | sort -hr | head -10
        uname -m  # Bonus: Confirms x64 vs. aarch64

    - name: Releases cleanup
      if: github.event.inputs.CLEAN_ENVIRONMENT == 'true'
      uses: Nats-ji/delete-old-releases@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        keep-count: 5
        remove-tag: true
        keep-old-minor-releases: false
        keep-old-minor-releases-count: 5
    
    - name: Free disk space
      run: |
        # docker rmi $(docker images -f "dangling=true" -q) || docker system prune -af || true
        docker system prune -f 2>&1 || docker system df 2>&1 || echo "::notice::docker $?"
        sudo rm -rf \
        /usr/share/dotnet /usr/local/lib/android /opt/ghc \
        /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
        /usr/lib/jvm "$AGENT_TOOLSDIRECTORY" || true
        echo "some directories deleted"
        sudo apt install aptitude -y >/dev/null 2>&1
        sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
        esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
        google-cloud-sdk imagemagick \
        libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
        mercurial apt-transport-https mono-complete libmysqlclient \
        unixodbc-dev yarn chrpath libssl-dev libxft-dev \
        libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
        snmp pollinate libpq-dev postgresql-client powershell ruby-full \
        sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
        -y -f >/dev/null 2>&1
        sudo aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
        sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
        sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
        sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
        sudo aptitude purge '~n ^php' -f -y >/dev/null 2>&1
        sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
        sudo apt-get autoremove -y >/dev/null 2>&1
        sudo apt-get autoclean -y >/dev/null 2>&1
        echo "some packages purged"
          
    - name: Check disk space again 
      run: |
        sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr 2>/dev/null | head -n 20
        sudo df -h
        sudo rm -rf /opt/hostedtoolcache/ && \
        sudo rm -rf /tmp/* && \
        sudo find /home/runner/actions-runner/cached/ -xdev -type f -size +250M -delete 2>/dev/null && \
        sudo find /var/log -xdev -name "*.gz" -mtime +10 -delete && \
        sudo df -h /
        sudo rm -rf /home/runner/work/device_alps_tb8163p3_bsp/device_alps_tb8163p3_bsp/workspace/prebuilts/go/linux-x86//bin/go
        export GOOS=linux
        export GOARCH=arm
        export GOARM=7
        mkdir -p /home/runner/work/device_alps_tb8163p3_bsp/device_alps_tb8163p3_bsp/workspace/prebuilts/go/linux-x86/bin
        go mod init "${{ github.event.inputs.BUILD_TARGET }}"image
        sudo wget -qO 'go1.26.1.linux-armv6l.tar.gz' 'https://go.dev/dl/go1.26.1.linux-armv6l.tar.gz' >/dev/null;
        sudo tar xf 'go1.26.1.linux-armv6l.tar.gz' -C '/home/runner/work/device_alps_tb8163p3_bsp/device_alps_tb8163p3_bsp/workspace/prebuilts/go/linux-x86/bin/' 'go' && rm -vrf 'go1.26.1.linux-armv6l.tar.gz' && echo -e "\ngo1.26.1.linux-armv6l.tar.gz --- Was Installed Successfully";
        sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr 2>/dev/null | head -n 20
        
    - name: Clone Recovery Repo
      uses: actions/checkout@v6
      with:
        repository: ${{ github.repository }}
        path: ./workspace/${{ github.event.inputs.DEVICE_PATH }}
        ref: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
      
    - name: cleanup old action artifacts
      if: github.event.inputs.CLEAN_ENVIRONMENT == 'true'
      run: | 
        gh extension install andyfeller/gh-artifact-purge
        gh artifact-purge ${{ github.repository }} 1
      continue-on-error: true
      
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup environment 
      if: github.event.inputs.CLEAN_ENVIRONMENT == 'true'
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps  

    - name: Maximize build space
      if: github.event.inputs.MAXIMIZE_BUILD_SPACE == 'true'
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 12000 # Example: Reserve 12 GB for the root directory
        swap-size-mb: 1024 # Example: Reserve 4 GB for swap file
        remove-dotnet: 'true' # Example: Remove the .NET SDK to free space 
      continue-on-error: true
        
    - name: Prepare The Environment
      run: |
        sudo apt-get -yqq update
        # sudo apt-get -y upgrade
        # sudo apt-get -y install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 unzip fontconfig
        # sudo apt-get -y install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig git repo liblzma-dev m4 libstdc++
        sudo apt-get -yqq install zip unzip fontconfig gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib lib32ncurses5-dev x11proto-core-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev golang-go >/dev/null;
        sudo add-apt-repository universe
        sudo apt-get -yqq install libncurses5
      continue-on-error: true

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8

    - name: Install Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Check Manifest Branch
      uses: haya14busa/action-cond@v1
      id: manifest
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1'  || github.event.inputs.MANIFEST_BRANCH == 'twrp-14.1' }}
        if_true: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
        if_false: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git

    - name: Initialize Repo
      run: |
        mkdir -p workspace
        cd workspace
        git config --global user.email "${GitHubMail}"
        git config --global user.name "${GitHubName}"
        git config --global credential.helper store
        repo init --depth=1 -u ${{ steps.manifest.outputs.value }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      continue-on-error: false    
  
    - name: Repo Sync
      run: |
        cd workspace
        repo sync -j$(nproc) --force-sync
        cd ./${{ github.event.inputs.DEVICE_PATH }}
        gh cache delete --all >/dev/null || echo 'No gh program found in system'

    - name: Check Build Makefile
      run: |
        cd workspace
        if [ -f ${{ github.event.inputs.DEVICE_PATH }}/twrp_${{ github.event.inputs.DEVICE_NAME}}.mk ]; then
            echo "DEVICE_MAKEFILE=twrp_${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        elif [ -f ${{ github.event.inputs.DEVICE_PATH }}/omni_${{ github.event.inputs.DEVICE_NAME}}.mk ]; then
            echo "DEVICE_MAKEFILE=omni_${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        else
            echo "::error::No device name makefile file found!"
        fi
      continue-on-error: false
      
    - name: Install Python 2
      if: github.event.inputs.MANIFEST_BRANCH != 'twrp-11' && github.event.inputs.MANIFEST_BRANCH != 'twrp-12.1'  && github.event.inputs.MANIFEST_BRANCH != 'twrp-14'
      run: |
        sudo apt-get -y -q -q install python2
        cd /usr/bin
        sudo ln -vsf python2 python

    - name: Building Image 
      run: |
        # sudo rm -rf /opt/hostedtoolcache && \
        sudo df -h /
        cd workspace
        # [[ -e ./build/make/core/Makefile ]] && [[ -e ./${{ github.event.inputs.DEVICE_PATH }}/scripts/mkimage ]] && sudo chmod 0755 ./${{ github.event.inputs.DEVICE_PATH }}/scripts/mkimage && sed -i '1525a \\t$(hide) $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mkimage $@ $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mtk_ramdisk.cfg > $@.mtk && mv -vf $@.mtk $@' ./build/make/core/Makefile && \
        #  grep -q "mtk_ramdisk.cfg" ./build/make/core/Makefile && \
        #  echo -e "\nChange verified!" || echo -e "\nEdit failed: string not found.";
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export RECOVERY_VARIANT=twrp
        export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
        export LC_ALL=C
        lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc) && \
        echo "Done building your ${{ github.event.inputs.BUILD_TARGET }}.img";
      
    - name: Set Build Date # Output will be use in Release
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        DEVICE_TREE_URL="${{ github.event.inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV

    - name: Check if Recovery Exist
      run: |
        cd workspace
        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img ]; then
            echo "RECOVERY_TYPE=recovery" >> $GITHUB_ENV
            echo "recovery.img file found!"
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/boot.img ]; then
            echo "RECOVERY_TYPE=boot" >> $GITHUB_ENV
            echo "boot.img file found!"
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img ]; then
            echo "RECOVERY_TYPE=vendor_boot" >> $GITHUB_ENV
            echo "vendor_boot.img file found!"
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
            echo "No Recovery file found!"
            cd Exit
        fi

    - name: Include Recovery Installer
      run: |
        if [ ${{ github.event.inputs.RECOVERY_INSTALLER }} = true ]; then
          cd workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/
          wget https://github.com/kinguser981/recovery-installer/releases/download/zip/recovery-installer.zip
          zip -ur recovery-installer.zip ${{ env.RECOVERY_TYPE }}.img
        fi
      continue-on-error: false
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery-installer.zip
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ env.RECOVERY_TYPE }}.img
        name: Unofficial TWRP for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
    - name: Release ramdisk-recovery
      uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/obj/PACKAGING/vendor_ramdisk_fragments_intermediates/recovery.*
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/ramdisk-recovery.*
        name: Unofficial TWRP for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Target: ${{ github.event.inputs.BUILD_TARGET}}.img
          Device: [Device Tree/Branch](${{ env.DEVICE_TREE_URL }}/${{ github.eventinputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }}) during building.
          MD5 (img): ${{ env.MD5_IMG }}
      continue-on-error: false
