name: Workflow Space Cleaner 2025

on:
  workflow_dispatch:
    inputs:
      OPERATE_SUDO:
        type: choice 
        description: Use sudo command
        options:
        - 'True'
        - 'False'
        required: true
        default: 'True'
      DOCKER_PRUNE:
        type: choice
        description: Docker prune
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      DOCKER_CLEAN:
        type: choice
        description: Docker clean
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      APT_PRUNE:
        type: choice
        description: Apt prune
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      APT_CLEAN:
        type: choice
        description: Apt clean
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      HOMEBREW_PRUNE:
        type: choice
        description: Homebrew prune
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      HOMEBREW_CLEAN:
        type: choice
        description: Homebrew clean
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      NPM_PRUNE:
        type: choice
        description: Npm prune
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      NPM_CLEAN:
        type: choice
        description: Npm clean
        options:
        - 'True'
        - 'False'
        required: true
        default: 'False'
      OS_SWAP:
        type: choice
        description: OS swap 
        options:
        - 'True'
        - 'False' 
        required: true
        default: 'True'


jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
    - name: Display Cleaner Run Parameters
      run: |
        echo "Fixes no disk space left when running workflows"
        echo "#"
        echo "::group::User Environment Variables"
        echo "OPERATE SUDO: ${{ inputs.OPERATE_SUDO }}"
        echo "GENERAL INCLUDE: .+"
        echo "DOCKER INCLUDE:  .+"
        echo "DOCKER PRUNE: ${{ inputs.DOCKER_PRUNE }}"
        echo "DOCKER CLEAN: ${{ inputs.DOCKER_CLEAN }}"
        echo "APT PRUNE: ${{ inputs.APT_PRUNE }}"
        echo "APT CLEAN: ${{ inputs.APT_CLEAN }}"
        echo "HOMEBREW PRUNE: ${{ inputs.HOMEBREW_PRUNE }}"
        echo "HOMEBREW CLEAN: ${{ inputs.HOMEBREW_CLEAN }}"
        echo "NPM_PRUNE: ${{ inputs.NPM_PRUNE }}"
        echo "NPM CLEAN: ${{ inputs.NPM_CLEAN }}"
        echo "OS SWAP: ${{ inputs.OS_SWAP }}"
        echo "::endgroup::"

    - name: Optimize Disk Space
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.0"
      with:
          operate_sudo: "${{ inputs.OPERATE_SUDO }}"
          general_include: ".+"
          docker_include: ".+"
          docker_prune: "${{ inputs.DOCKER_PRUNE }}"
          docker_clean: "${{ inputs.DOCKER_CLEAN }}"
          apt_prune: "${{ inputs.APT_PRUNE }}"
          apt_clean: "${{ inputs.APT_CLEAN }}"
          homebrew_prune: "${{ inputs.HOMEBREW_PRUNE }}"
          homebrew_clean: "${{ inputs.HOMEBREW_CLEAN }}"
          npm_prune: "${{ inputs.NPM_PRUNE }}"
          npm_clean: "${{ inputs.NPM_CLEAN }}"
          os_swap: "${{ inputs.OS_SWAP }}" 

    - name: Disk Space Check
      run: |
        sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
        echo "#"
        df . -h
        echo "#"
        sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head

    - name: Disk Cleanup Done
      run: echo "Workflow storage space cleaning was completed... GoodBye"
      
